language: php

php:
  - 7.2

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer install --no-interaction

script:
  - php artisan key:generate
  - vendor/bin/phpunit


services:
  - redis-server

cache:
  directories:
    - vendor